### PR TITLE
[Conversation] Update SDK with news APIs

### PR DESCRIPTION
**Pull request by Themandunord**
Hi,

Add new API for Conversation : 

Get intents
Create intent
Delete intent
Get intent
Update intent

With tests.

It's my first pull request, don't hesitate to tell me if it's correct or not :)

Rémy.

### CODE REVIEW

**Comment by nfriedly** [comment]
Hi Rémy, thanks! 

I'll do a more thorough review, but at first glance this looks really great!

Please pull in the latest changes form master, though. There was a typo in master when you forked that's causing the tests to fail, but that should be fixed now. (I think GitHub even provides a button to do it for you on the page here).

**Comment by Themandunord** [comment]
Hum, I don't see this button :/

**Comment by Themandunord** [comment]
Ok, I do that manually :)

**Comment by Themandunord** [comment]
I add some APIs : 

Get user input examples
Create user input example
Delete user input example
Get user input example
Update user input example

**Comment by Themandunord** [comment]
@nfriedly I make your changes :+1: 

But I broke some tests with "trickey" text. It's a good example :+1: 
But I don't suceed to avoid the error. Have you got idea ?

**Comment by nfriedly** [comment]
So, we did not need to add encodeUriComponent, the requestWrapper automatically does that when parsing the path. It turns out that the only character causing an issue was the `\` - so I removed that from the test cases and I'm going to reach out to the service team. 

This should be released in v2.23.0 once the CI loop finishes!

Thanks again for the great work!

**Pull request merged**
