### PR TITLE
support gzip

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by germanattanasio** [comment]
Thanks for the pull request. Did you check that the service is returning the data compressed?
I think we are not supporting compression in our services yet.

**Comment by Kikobeats** [comment]
You're right, nothing about gzip support in the headers of the API server... any plan for this? :_(

**Comment by germanattanasio** [comment]
Compression support is something we are working on. I will keep this open and merge it once our servers support it.

Thanks

**Comment by germanattanasio** [comment]
Almost a year @Kikobeats :see_no_evil:

**Comment by Kikobeats** [comment]
Officially is supported? 🎉🎉

**Comment by germanattanasio** [comment]
It's not supported yet but we are close

**Pull request merged**
