### PR TITLE
[document-conversion] Adds index document API

### PR DESCRIPTION
**Pull request by samir-patel**
### Summary

This submission includes new API call for the Document Conversion Service that will allow you to access the index_document endpoint:

DocumentConversion.prototype.index

This is a synchronous call that will allow you to convert and index a document into a SOLR collection (via the Retrieve and Rank service) in one operation.  A "dry run" of the indexing can be submitted to preview the indexed results prior to actual indexing.

### CODE REVIEW

**Comment by germanattanasio** [comment]
@nfriedly do we get `lint` to check that the `jsdoc` is valid ?

**Comment by germanattanasio** [comment]
This looks OK for me

**Comment by nfriedly** [comment]
@germanattanasio we have the [ESLlint rule disabled](https://github.com/watson-developer-cloud/node-sdk/blob/master/.eslintrc.js#L206) but we do run the [doc build on travis](https://github.com/watson-developer-cloud/node-sdk/blob/master/.travis.yml#L9) as part of the tests and it looks like [this one passed](https://travis-ci.org/watson-developer-cloud/node-sdk/jobs/142507867#L836)

**Comment by nfriedly** [comment]
Hey @samir-patel, sorry it took me a couple of days to get to this; do you think you can add a basic "happy case" unit test?

**Pull request merged**
