### PR TITLE
[Discovery] Allow to update existings documents

### PR DESCRIPTION
**Pull request by pudelduscher**

### CODE REVIEW

**Comment by pudelduscher** [comment]
@germanattanasio i hope this is what you want

**Comment by germanattanasio** [comment]
This looks good. One more thing, can you do me a favor and update `query_params` to be `queryParams`? I know it wasn't you but since you are modifying the file.

**Comment by pudelduscher** [comment]
@germanattanasio should i update it everywhere or just in the update method?

**Comment by germanattanasio** [comment]
In every method withing the discovery file.

**Pull request merged**
