### PR TITLE
Snyk is dev dependency

### PR DESCRIPTION
**Pull request by Naktibalda**
Snyk is dev-dependency, I don't want to get it installed with `ibm-watson`.

### CODE REVIEW

**Comment by dpopp07** [comment]
Hey @Naktibalda, this was actually [changed already in the release branch](https://github.com/watson-developer-cloud/node-sdk/blob/release-v5-rc2/package.json#L70) which should be getting merged in today or tomorrow. So I'm going to close this PR but thank you for opening!

**Comment by Naktibalda** [comment]
@dpopp07 that release branch is for v5, is there any chance to get that change applied to v4?

**Comment by dpopp07** [comment]
@Naktibalda Yes, we can definitely do that. I will cherry pick the commit from the v5 branch and release it with a v4 tag.

Right now, I am focused on releasing v5 but should be able to get that patch out tomorrow or Monday.

**Comment by dpopp07** [comment]
@Naktibalda This is available now in `ibm-watson@4.5.2`

**Pull request closed without merging**
