### PR TITLE
Conv 329

### PR DESCRIPTION
**Pull request by Mikemosca**
For Conversation

Add a few new unit tests
Add a new integration test

### CODE REVIEW

**Comment by Mikemosca** [comment]
Hi,

I also modified auth.js to add an entry for conversation.  German said you might be able to encrypt it put it in git for me.  I will include it here

**Comment by Mikemosca** [comment]
So the upload does not support a .js file.  I changed it to auth.txt to upload it.  It will need to be changed back to auth.js b4 sourced to git.

[auth.txt](https://github.com/watson-developer-cloud/node-sdk/files/464485/auth.txt)

**Comment by nfriedly** [comment]
@Mikemosca I deleted your last post because this is a public repo - anyone on the internet could have gone and downloaded those credentials. Please send them over email or slack or similar.

**Comment by nfriedly** [comment]
Also, did you run `npm test` locally? I'm getting a few lint errors.

**Comment by nfriedly** [comment]
(I went ahead and patched things up, it was pretty straightforward. Thanks for writing the tests!)

**Comment by Mikemosca** [comment]
Thanks for the comments and for patching it up.  I will be aware of the public repo for the next one.

Mike

**Pull request merged**
