### PR TITLE
update retrieve and rank

### PR DESCRIPTION
**Pull request by germanattanasio**
### Update the retrieve and rank service implementation

@gjs29 Can you verify if `deleteCollection`, `createCollection` and `listCollections` are actually `GET` calls and not `POST` as described in:

* [swagger](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/apis/#!/retrieve-and-rank/adminAction)
screen shot 2015-10-11 at 12 40 39 pm

* [API Reference](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-and-rank/api/v1/#delete_solr_collection).
screen shot 2015-10-11 at 12 40 28 pm

I'm looking at the [Solr documentation](https://cwiki.apache.org/confluence/display/solr/Collections+API) and looks like those are `GET` requests but I want to make sure.

### CODE REVIEW

**Comment by gjs29** [comment]
Solr (and our service) will accept both POSTs and GETs for collection actions.

**Comment by germanattanasio** [comment]
should we use POST or GET in the sdk ?

**Comment by nfriedly** [comment]
Use GET when you're only fetching information (not making changes) and you can be fairly certain that the URL won't exceed ~2000 characters

**Comment by gjs29** [comment]
That sounds like GET for listCollections and POST for create and delete.

**Comment by nfriedly** [comment]
Yep

**Comment by germanattanasio** [comment]
I made delete and create to be POST

**Pull request merged**
