### PR TITLE
fix(stt): revert change to word_confidence made by 84bb18d

### PR DESCRIPTION
**Pull request by Hsaylor**
Second PR to fix STT `word_confidence` as a follow up to #1112

### CODE REVIEW

**Comment by repjarms** [comment]
@Hsaylor did we decide if we were going to do this? If I remember correctly, this is something we aren't going to override at this time. If that's the case we should close this.

**Comment by apaparazzi0329** [comment]
Well I looked over the `timestamp` and `word_confidence` properties and they are both currently incorrect, including this PR. We can create a quick patch if we think this needs to be addressed but the correct typing for each property, respectively, is `[string, number, number][]` and `[string, number][]`

**Comment by apaparazzi0329** [comment]
@Hsaylor let's do a quick patch release to address this

**Comment by Hsaylor** [comment]
Update pushed

**Review by apaparazzi0329 — APPROVED** [review]
lgtm

**Pull request merged**
