### PR TITLE
[docs] Revise PI deprecation, add VisRec deprecation

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary

This pull request updates personality insights deprecation message and adds visual recognition deprecation message

### CODE REVIEW

**Comment by jeffpk62** [comment]
@mediumTaj Oh, sure, mess with the terrible wording of my PI update, go ahead.  In my defense, I just did what I was told!!  :-)

**Comment by SirSpidey** [comment]
@jeffpk62 and in Taj's defense, he's just doing what _he_ was told 😺

**Comment by jeffpk62** [comment]
@SirSpidey @mediumTaj  Echos of Nuremberg.

**Review by SirSpidey — APPROVED** [review]
👍

**Review by apaparazzi0329 — APPROVED** [review]
LGTM

**Pull request merged**
