### PR TITLE
Release q3 2022

### PR DESCRIPTION
**Pull request by Hsaylor**
Assistant V1
 
 ### Models
 * RuntimeIntent: `confidence` is no longer a required parameter
 * Workspace: New status available: “processing”, new properties added: `statusErrors` and `counts`
 * WorkspaceSystemSettings: New property `nlp`
 
 ### Methods
 * NEW Method: `createWorkspaceAsync`
 * NEW Method: `updateWorkspaceAsync`
 * NEW Method: `exportWorkspaceAsync`
 
 ## Assistant V2
 ### Models
 * BulkClassifyOptions: add `input` as required property
 * MessageOutputDebug: add `turnEvents` property
 * RuntimeEntity: add `skill` property
 * RuntimeIntent: add `skill` property and `confidence` no longer a required property
 * RuntimeResponseGeneric: Date type added
 
 ### Methods
 * NEW Method: `listEnvironments`
 * NEW Method: `getEnvironments`
 * NEW Method: `listReleases`
 * NEW Method: `getRelease`
 * NEW Method: `deployRelease`
 
 ## Discovery V1
 * No changes
 
 ## Discovery V2
 ### Models
 * add parameter  `smartDocumentUnderstanding` to `createCollection`  and `updateCollection`
 * Enrichment: new type `clarifier`
 * add parameters `classifierId`, `modelId`, `confidenceThreshold`, `topK` to `createEnrichment` and `updateEnrichment`
 * add parameter `similar` to `query`
 
 ### Methods
 * NEW Method: `listDocuments`
 * NEW Method: `getDocument`
 * NEW Method: `listDocumentClassifiers`
 * NEW Method: `createDocumentClassifier`
 * NEW Method: `getDocumentClassifier`
 * NEW Method: `updateDocumentClassifier`
 * NEW Method: `deleteDocumentClassifier`
 * NEW Method: `listDocumentClassifierModels`
 * NEW Method: `createDocumentClassifierModel`
 * NEW Method: `getDocumentClassifierModel`
 * NEW Method: `updateDocumentClassifierModel`
 * NEW Method: `deleteDocumentClassifierModel`
 * NEW Method: `getStopwordList`
 * NEW Method: `createStopwordList`
 * NEW Method: `deleteStopwordList`
 * NEW Method: `listExpansions`
 * NEW Method: `createExpansions`
 * NEW Method: `deleteExpansions`
 
 ## LT
 * Nothing
 
 ## NLU
 ### Models
 * add parameter `trainingParameters` to `createClassificationsModel` and `updateClassificationsModel`
 
 ## STT
 ### Models
 * Remove parameter `customizationId`  from  `createJob` and `recognize`
 * Add parameter `characterInsertionBias` to `createJob` and `recognize`
 * Add parameter `strict` to `trainAcousticModel` and `trainLanguageModel`
 
 ## TTS
 ### Models
 * Add parameter  `spellOutMode` to `synthesize`

### CODE REVIEW

**Review by apaparazzi0329 — APPROVED** [review]
LGTM!

**Comment by apaparazzi0329** [comment]
https://user-images.githubusercontent.com/26935099/183744509-dda695c8-e0ad-4097-aa09-90dc637d9d97.gif

**Comment by apaparazzi0329** [comment]
https://media2.giphy.com/media/njpterp1OxZOgX7CI4/giphy.gif

**Comment by apaparazzi0329** [comment]
temp

**Review by Hsaylor — COMMENTED** [review]
thanks for the sockets update!

**Pull request merged**
