### PR TITLE
Update mic stream example

### PR DESCRIPTION
**Pull request by dpopp07**
During a support session, I discovered that the example for using STT to stream from the microphone to the console was broken. This was due to the `interim_results` parameter not being passed in as `true`, as it defaults to `false`.

I updated the example to use the correct parameter and changed the JSDocs for `RecognizeStream` because they incorrectly listed the default value for `interim_results` as `true`.

ref:

From the [Speech to Text](https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#websocket_methods) docs:
> **interim_results**
If `true`, the service returns interim results as a stream of JSON `SpeechRecognitionResults` objects. If `false`, the service returns a single `SpeechRecognitionResults` object with final results only.
Default: `false`

cc @jeffpk62

### CODE REVIEW

**Comment by dpopp07** [comment]
You mean the `package.json` for the `examples/` folder?

It has the line `"watson-developer-cloud": "*",` which should always be pulling in the latest version.

**Comment by anweshan** [comment]
@dpopp07 No, I mean the package.json in the `examples/speech_to_text_microphone_input` folder which should be changed to what you said above

**Comment by anweshan** [comment]
Actually I just noticed that all the package.json files inside the examples folder inside the examples that have their own package.json inside their individual folder should probably be updated with that

**Comment by dpopp07** [comment]
Also, I verified that the examples work with the updated SDK versions.

**Comment by jeffpk62** [comment]
@dpopp07 Sorry for not seeing that comment about `interim_results` sooner.  I'd have pointed it out otherwise.  The API reference has the correct default (`false`).

**Comment by dpopp07** [comment]
@jeffpk62 No worries! I just tagged you so you would be aware of the fix.

All - holding off on merge until #762 is merged, since that should prevent the build on `master` from failing.

**Comment by qunliu** [comment]
Is there a similar issue with another sample STT code? (https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/speech_to_text_microphone_input/transcribe-mic-to-file.js)

I pulled down the sample code and ran it, the recorded mic wav file sounds funny (like a slow mo recording where I record 2 seconds, but it gives me 8 seconds or something). However, I put interim_results there doesn't help. Did I miss anything else? Would you please take a look? Thanks!

**Comment by dpopp07** [comment]
Hi @qunliu, I tested that example and found that it was not affected by the above problem. This example is for listening to audio from the microphone and writing the transcribed words to a text file. You should not be expecting an audio file.

If you are having trouble with a text-to-speech example, please open an issue with your code and I will be happy to take a look!

**Comment by qunliu** [comment]
Thanks for looking into it @dpopp07 I am a still bit confused. If I understand this example correctly, it does a few things (please see the screenshot below):
* Listen to a mic and get audio stream from it;
* Pipe this audio stream to a file writer and get an audio file written to disk;
* Pipe the audio stream once again to Watson speech to text service and once the transcription is back, it gets written to a file (note: I am not looking at text to speech).

In my test, the transcription was all wrong, so that's where I started looking at that audio file recorded on disk and noticed that was wrong as well which in turn gave wrong transcription.

Sorry if I totally misunderstood the example. Please let me know what you think.

Thanks!

image

**Comment by dpopp07** [comment]
Hi @qunliu, I now see what you are saying. I misunderstood your problem at first. Thank you for clarifying. I opened an issue to track this while I investigate - Please reference #765

**Pull request merged**
